### ISSUE TITLE
Tool Bibi can view epub offset page?

### ISSUE THREAD

**Issue by huyvodl** [satorumurmur/bibi#31]
My epub have total: 20 page .I want to prevent view epub offset: page 1->5. Tool Bib have support? Thanks!

**Comment by satorumurmur** [comment]
Now you can set nombre disabled in preset `bib/i/presets/default.js`.
But you can not hide only percentages or the total number of pages, or display the number of HTML files instead of the number of pages. I would like to make it a future issue.
(I'm sorry but I couldn't understand the 'page 1->5' or 'epub offset' you told.)
