### ISSUE TITLE
Can't connect Google Analytics

### ISSUE THREAD

**Issue by pizzakid25** [satorumurmur/bibi#83]
I can't figure out how to enable the Analytics extension. I tried to follow the instructions, but just can't figure out where to put the Tracking ID.

**Comment by satorumurmur** [comment]
Usage:
```
"extensions": [
    { "src": "../extensions/analytics.js", "tracking-id": "XXXXXXXXXX" }
""],
```

Sorry for the lack of the documentation.

The analytics.js extension is a kind of a sample. So if you want to track users reading-activities, you have to customize the extension.

If you simply want to use Google Analytics for access logs, you can just add the GA tag to bibi/index.html as same as a typical website, instead of using the extension.
